version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flash_sale_app
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    restart: on-failure

  db:
    image: postgres:9.6
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=flash_sale
      - POSTGRES_DB=flash_sale
      - POSTGRES_PASSWORD=flash_sale
    restart: on-failure

  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - 6379:6379
    restart: on-failure