definitions:
  request.CreateSaleRequest:
    properties:
      discount:
        type: number
      endTime:
        type: string
      product_id:
        type: integer
      saleStock:
        type: integer
      startTime:
        type: string
    required:
    - discount
    - endTime
    - product_id
    - saleStock
    - startTime
    type: object
  request.UpdateSaleRequest:
    properties:
      active:
        type: boolean
      discount:
        type: number
      endTime:
        type: string
      id:
        type: integer
      saleStock:
        type: integer
      startTime:
        type: string
    required:
    - id
    type: object
  response.SaleResponse:
    properties:
      active:
        type: boolean
      discount:
        type: number
      endTime:
        type: string
      product_id:
        type: integer
      saleStock:
        type: integer
      startTime:
        type: string
    type: object
info:
  contact:
    email: jerdem.akyildiz@gmail.com
    name: Flash Sale Management
paths:
  /flash-sales:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            items:
              $ref: '#/definitions/response.SaleResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get Flash All Sale
      tags:
      - Sales
    post:
      consumes:
      - application/json
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateSaleRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.SaleResponse'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create Flash Sale
      tags:
      - Sales
    put:
      consumes:
      - application/json
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UpdateSaleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/response.SaleResponse'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Update Flash Sale
      tags:
      - Sales
  /flash-sales/{id}:
    delete:
      parameters:
      - description: Flash Sale ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Ok
      summary: Delete Flash Sale
      tags:
      - Sales
    get:
      parameters:
      - description: Flash Sale ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/response.SaleResponse'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get Flash Sale
      tags:
      - Sales
  /flash-sales/{id}/buy:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: Ok
      summary: Buy Product
      tags:
      - Sales
swagger: "2.0"
